sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
    - NODE_ENV="test"
    - NSQ_DOCKERS="cluster"
node_js:
  - "10"
  - "8"
services:
  - docker
install:
  - yarn
before_script:
  - ./dockers/up.sh
script:
  - make test-coveralls
